enable-magisk-update = true

patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "lat rvx"

[YouTube]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
app-name = "YouTube"
build-mode = "both"
version = "auto"
included-patches = "'Add splash animation' 'MaterialYou' 'Spoof app version'"
excluded-patches = "'Custom branding icon YouTube' 'Custom branding name YouTube' 'Custom package name' 'Disable HDR video' 'Spoof player parameters' 'Theme' 'Enable debugging'"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
version = "auto"
build-mode = "apk"
app-name = "Reddit"
