enable-magisk-update = true

patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "lat rvx"

[YouTube]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
app-name = "YouTube"
build-mode = "both"
version = "19.11.38"
included-patches = "'Add splash animation' 'MicroG support' 'MaterialYou'"
excluded-patches = "'Custom branding icon YouTube' 'Custom branding name YouTube' 'Custom package name' 'Disable HDR video' 'Spoof app version' 'Spoof player parameters' 'Theme'"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
version = "auto"
build-mode = "apk"
app-name = "Reddit"
